#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/fluidasfack.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf fluidasfack.tar.gz
echo "unzip done"
find fluidasfack.tar.gz -delete
