#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/ccache-folos.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache-folos.tar.gz
echo "unzip done"
find ccache-folos.tar.gz -delete
